// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ToUpperClient is the client API for ToUpper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToUpperClient interface {
	Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error)
}

type toUpperClient struct {
	cc grpc.ClientConnInterface
}

func NewToUpperClient(cc grpc.ClientConnInterface) ToUpperClient {
	return &toUpperClient{cc}
}

func (c *toUpperClient) Upper(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error) {
	out := new(UpperReply)
	err := c.cc.Invoke(ctx, "/proto.ToUpper/Upper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToUpperServer is the server API for ToUpper service.
// All implementations must embed UnimplementedToUpperServer
// for forward compatibility
type ToUpperServer interface {
	Upper(context.Context, *UpperRequest) (*UpperReply, error)
	mustEmbedUnimplementedToUpperServer()
}

// UnimplementedToUpperServer must be embedded to have forward compatible implementations.
type UnimplementedToUpperServer struct {
}

func (UnimplementedToUpperServer) Upper(context.Context, *UpperRequest) (*UpperReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upper not implemented")
}
func (UnimplementedToUpperServer) mustEmbedUnimplementedToUpperServer() {}

// UnsafeToUpperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToUpperServer will
// result in compilation errors.
type UnsafeToUpperServer interface {
	mustEmbedUnimplementedToUpperServer()
}

func RegisterToUpperServer(s grpc.ServiceRegistrar, srv ToUpperServer) {
	s.RegisterService(&ToUpper_ServiceDesc, srv)
}

func _ToUpper_Upper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToUpperServer).Upper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ToUpper/Upper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToUpperServer).Upper(ctx, req.(*UpperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToUpper_ServiceDesc is the grpc.ServiceDesc for ToUpper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToUpper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ToUpper",
	HandlerType: (*ToUpperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upper",
			Handler:    _ToUpper_Upper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toupper.proto",
}
